AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Env:
    Type: String
Description: sample
Resources:
  s3:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${Env}
